<<fig_model, cache=FALSE, include=TRUE, echo=FALSE, warning=FALSE, error=FALSE, results="hide", fig.pos="t", fig.height=2.5, fig.width=5, dev=c("postscript","pdf"), dev.args=list(pointsize=7), background=NA>>=

library(mstherm)

cols <- brewer.pal(9,"Set1")

expt.atp <- MSThermExperiment("../R/control.atp", "../R/TAIR10_annots.tsv")
expt.atp <- normalize_to_std(expt.atp, "sp_ALBU_BOVIN_", plot=F)
res.atp.nonorm <- model_experiment(expt.atp, "AT3G48990", min_tot_psm=5, min_smp_psm=2, max_inf=0.3, bootstrap=T, check_missing=T, smooth=T, only_modeled=T, max_slope=-0.03, min_r2=0.7, min_pep=1)

par(
    mfrow = c(1, 2),
    mgp = c(2.2, 0.7, 0),
    mar=c(3.5,3.5,0.5,0.5),
    oma=c(0,0,1.5,1.5)
)

p <- 0
k <- 700
m <- 42

x <- seq(20,65,by=0.1)
y.sig <- eval(mstherm:::sigmoid,list(p=0,k=k,m=m,x=x))
y.sig.d1 <- eval(mstherm:::sigmoid.d1,list(p=0,k=k,m=m,x=x))
plot(x,y.sig,ylim=c(-.2,1.2),xlab="temperature (°C)",ylab="relative soluble fraction", type="l",lwd=3)
lines(x,y.sig.d1,lty=5,col=cols[2])
#abline(v=m,lty=5,col=cols[1])
lines(c(m,m), c(-0.3,0.9),lty=5,col=cols[1])
abline(h=0.5,lty=5,col=cols[3])
slope <- eval(mstherm:::sigmoid.d1,list(p=0,k=k,m=m,x=m))
b <- 0.5 - slope*m
abline(b,slope,lty=5,col=cols[4])
text(38,1,expression(P == frac({1-p},1+e^{-k*(x^-1-m^-1)})+p),pos=4,cex=1.1)
mtext("(a)", side = 3, adj = 0.05, line = -1.3, font=2)

plot(res.atp.nonorm,header=F)

mtext("(b)", side = 3, adj = 0.05, line = -1.3, font=2)

@
